vsgg12/VSGG-FE

src/app/post/write/_component/PostUploadFile.tsx
=> Refactor: 게시물 등록 페이지 링크 첨부 삭제

package-lock.json, package.json, src/app/globals.css, src/app/home/_component/HomeNotVoted.tsx, src/app/home/_component/HomeVoted.tsx, src/app/home/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/_component/VoteForm.tsx, src/app/post/_component/VoteResult.tsx, src/app/post/_component/VotingGraph.tsx, src/components/DoughnutChart.tsx, src/components/Search.tsx
도넛차트가 게시글 상세 페이지에서도 쓰이는데 사이즈가 달라야해서 size props 추가하고 
Home 페이지에서 사용하는 도넛에 props로 size='home' 넘겨줌
아 그리고 일단 홈이랑 게시글 상세 페이지 mx 만 동일하게 맞춰둠
=> style: post detail page

public/svg/deleteIcon.svg, src/app/signUp/page.tsx
=> Style: 회원가입 페이지 퍼블리싱 및 간단한 기능 구현 완료(api 구현은 아직)

src/api/naver/naverLogin.ts, src/app/home/_component/HomePostItems.tsx, src/app/login/naver/page.tsx, src/app/login/page.tsx, src/app/post/[postId]/page.tsx, src/hooks/useConvertHTML.tsx
메인 페이지 html 추출해서 P태그 부분만 보이게 수정
=> feat: useConvertHtml

src/api/postVote.ts, src/app/post/[postId]/page.tsx, src/app/post/[postId]/store/usePostIdStore.ts, src/app/post/_component/Comment.tsx, src/app/post/_component/VoteForm.tsx, src/app/post/_component/VoteResult.tsx, src/app/post/_component/VotingGraph.tsx, src/types/get.d.ts, src/types/post.d.ts
답글 닉네임 호춟부분 ui
투표 api 연동
사용 안하는 변수 정리
=> fix: comment & feat: vote api

src/api/postVote.ts, src/app/post/[postId]/page.tsx, src/app/post/_component/VotingGraph.tsx
=> fix:post vote

src/app/home/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/_component/PostCommentInput.tsx, src/app/post/_component/ReplyInput.tsx, src/app/post/_component/VoteForm.tsx, src/components/Search.tsx
=> feat: 비로그인 상태 처리

src/api/PostSignUp.ts, src/api/getPostItem.ts, src/api/getPostList.ts, src/app/home/page.tsx, src/app/login/naver/page.tsx, src/app/login/store/useAuthStore.ts, src/app/post/[postId]/page.tsx, src/app/post/_component/VoteResult.tsx, src/app/signUp/page.tsx
useAuthStore에 user 객체 추가,
isVote값에 따른 게시글 목록, 게시글 상세 페이지 화면 수정
=> fix: useAuthStore & isVote status

src/app/home/page.tsx
<div ref={loaderRef} style={{ minHeight: '30px' }} /> 
observer의 기준이 되는 div의 minHeight가 충분하지 않으면 다 못불러옴
=> Feat: 메인페이지 5개씩 게시글 보여주는 무한스크롤 구현 완료

src/app/post/write/_component/PostFe.tsx
문제점: 사용자가 이미지를 업로드하고 삭제해도 contentImgUrls 배열엔 그대로 남아있음. 배열에서도 삭제를 해야하는데 방법을 모르겠음
=> fix: 해시태그 12글자 제한, 이미지 업로드 개수 3개 제한

src/_lib/fetcher.ts, src/_lib/refreshTokenExpired.ts, src/api/postRefresh.ts
fix: 401 에러 발생했을떄 에러처리가 무한 반복되는 오류 수정 작업 및 어느부분에서 오류가 나는지 확인을 위한 코드 곳곳에 콘솔 로그 추가
=> main 최신화 및 재배포

package-lock.json, package.json, src/app/layout.tsx, src/app/post/write/_component/PostFe.tsx, src/types/post.d.ts, tsconfig.json
게시글 작성 페이지에서 postFormData의 데이터값을 보기 위한 target 설정
quill 업데이트
게시글 작성 페이지 api 연동 수정 작업 완료(voteEndDate 추가)
=> Fix: 게시글 작성 페이지 api 연동 수정 작업 완료(voteEndDate 추가)

public/svg/postListsIcon.svg, public/svg/videoPostListsIcon.svg, src/app/home/_component/HomePostItems.tsx, src/app/home/page.tsx, src/app/layout.tsx, src/app/robots.txt
- 메인페이지 영상 게시글 목록에서 게시글들의 width가 작은 오류 수정
-  robot.txt에 User-agent를 googlebot에 한정되어 있던것을 * 전체로 바꿈
- seo 작업 중 canonical 추가
- 영상 게시글 목록아이콘, 리스트형 목록아이콘 svg 파일 추가
- 메인 페이지에서 우측에 있던 "홈" 텍스트를 아이콘으로 수정
=> chore: seo 작업 및 스타일 수정

src/api/getMyProfileDTO.ts, src/app/myPage/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/_component/Comment.tsx, src/app/post/_component/PostCommentInput.tsx, src/app/post/_component/VoteForm.tsx, src/types/get.d.ts
1. 마이페이지 개인정보 조회하는 api 연동하는 로직만 짜놓음, 받아온 데이터 사용하는 로직은 추후에 구현 예정
2. 게시글 상세 페이지에서 voteForm 부분 min-width 설정
3. 댓글/대댓글 시간 표시와 더보기 부분 퍼블리싱 한 부분 일단 주석처리
4. 게시글 상세 페이지에서 비로그인 상태일때 댓글, 투표완료 버튼 누르면 로그인 알림 모달창이 뜨도록 수정작업
=> Feat: 마이페이지 개인정보 조회 api 연동 작업중

src/app/home/page.tsx, src/app/myPage/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/write/_component/Calendar.tsx, src/app/post/write/_component/PostFe.tsx, src/app/post/write/page.tsx
1. 달력 컴포넌트에서 화살표 눌렀을때 알림창뜨는 오류 수정
2. 달력 컴포넌트에서 최대 30일 이후의 날짜에는 disabled 처리, 월 표시 부분 07월 -> 7월 수정
3. 게시글 작성 페이지 전체 박스 최소 너비 조정 및 판결 날짜 설정 부분 레이아웃 오류 수정
4. 마이 페이지, 메인 페이지, 게시글 상세 페이지 min-width 설정
=> Style: 판결 설정 부분 오류 수정 및 모든 페이지 최소 너비 설정

src/api/getMyPostLists.ts, src/app/layout.tsx, src/app/myPage/_component/MyPostItem.tsx, src/app/myPage/_component/MyPostList.tsx, src/app/myPage/_component/VoteStatusCircle.tsx, src/app/myPage/myPosts/page.tsx, src/app/myPage/page.tsx, src/types/get.d.ts, src/utils/formatDate.ts
1. 마이페이지, 내가 쓴 글 페이지 api 연동 작업 및 스타일 조정
2. 마이페이지에서 사용되는 voteStatus와 voteResult 상태 원 컴포넌트 작업
3. 날짜 format 함수 공통함수 폴더로 뺴기
4. 내가 쓴글 목록과 아이템 컴포넌트화 작업
5. apple-touch-icon favicon.ico 파일로 수정
=> Feat: 내가 쓴 글 조회 api 연동 작업

src/app/post/[postId]/page.tsx, src/components/modals/MoreModal.tsx, src/types/get.d.ts
1. 더보기 모달 퍼블리싱
2. 게시글 상세 페이지에 추가된 더보기 모달 적용
3.  게시글 상세페이지 api reponse data에 isDelete 추가
=> Style: 더보기 모달 추가 및 게시글 페이지 적용

src/app/home/page.tsx, src/app/myPage/_component/MyJudgeList.tsx, src/app/myPage/_component/MyPostList.tsx, src/app/myPage/page.tsx, src/app/post/[postId]/page.tsx, src/types/get.d.ts
→ 이미 프론트에서는 데이터 받아와지기 전까지 로딩 스피너 보여주도록 로직 구현했는데 뭐때문인지 생긴 오류인지 모르겠음
=> Fix: 마이페이지, 메인페이지에서 생긴 일부 오류 수정

src/api/deleteComment.ts, src/app/post/[postId]/page.tsx, src/app/post/_component/Comment.tsx, src/app/post/_component/PostCommentInput.tsx, src/components/modals/MoreModal.tsx
게시물 상세 페이지 레이아웃 수정 및 댓글 삭제 기능 구현
=> Feat: delete comment 기능 구현

package-lock.json, package.json, src/app/post/[postId]/page.tsx, src/app/post/_component/Comment.tsx
build 에러 해결
- webpack 삭제
- 사용하지 않는 변수 처리
=> fix : build error

src/app/home/_component/HomePostItems.tsx, src/app/home/_component/HomeVoted.tsx, src/app/home/_component/ListedPostItem.tsx, src/app/home/_component/ProfileModal.tsx, src/app/post/_component/ContentArea.tsx, src/app/post/_component/VoteResult.tsx, src/components/Header.tsx
isOwner 여부 검사 닉네임 일치 검사 -> 이메일 일치 검사로 수정
=> Fix: 투표 컴포넌트 상황에 맞게 보여지도록 수정

src/app/home/_component/AlignModeToggleButton.tsx, src/app/home/_component/HomePostItems.tsx, src/app/home/_component/NewPopularToggleButton.tsx, src/app/home/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/_component/Comment.tsx, src/app/post/_component/CommentArea.tsx, src/app/post/_component/ContentArea.tsx, src/app/post/_component/NavigationArea.tsx, src/app/post/_component/PostCommentInput.tsx, src/app/post/_component/VoteArea.tsx, src/app/post/_component/VoteForm.tsx, src/app/post/_component/VoteResult.tsx, src/components/Header.tsx, src/components/Logo.tsx, src/components/modals/MoreModal.tsx
메인 페이지 컴포넌트화 & 게시물 상세 페이지와 메인페이지 레이아웃 수정
=> Style : main page, 게시물 상세 페이지 레이아웃 수정

src/app/post/_component/Comment.tsx, src/app/post/_component/CommentArea.tsx
targetCommentId, targetCommentNickname으로 분리되어 있던거 
targetComment 객체 하나로 합침
=> fix/ comment

src/app/myPage/mobile/judgeRecord/page.tsx, src/app/myPage/mobile/modifyProfile/page.tsx, src/app/myPage/mobile/myPosts/page.tsx, src/components/mobile/MobileHeader.tsx
=> Style: 모바일 버전의 프로필 변경 페이지 퍼블리싱 및 기능구현 완료

src/app/alert/page.tsx, src/app/myPage/_component/VoteStatusCircle.tsx, src/app/myPage/mobile/_component/MyJudgeItem.tsx, src/app/myPage/mobile/_component/MyPostItem.tsx, src/app/myPage/mobile/judgeRecord/page.tsx, src/app/myPage/mobile/modifyProfile/page.tsx, src/app/myPage/mobile/myPosts/page.tsx, src/app/myPage/mobile/page.tsx
피그마 상으로 내가 쓴글 모바일 페이지는 디자인이 확정되지 않았길래 임의로 PC버전과 비슷하게 했습니다
=> style: 모바일 버전 페이지들 전반적인 스타일 조정 및 내가쓴글, 판결전적 페이지 퍼블리싱 및 기능 구현 완료(판결전적, 내가쓴글 페이지는 무한 스크롤로 구현)

src/app/alert/mobile/page.tsx, src/app/globals.css, src/app/home/mobile/page.tsx, src/app/myPage/mobile/judgeRecord/page.tsx, src/app/myPage/mobile/myPosts/page.tsx, src/app/myPage/mobile/page.tsx, src/components/mobile/Headers/MainHeader.tsx, src/components/mobile/Headers/MobileHeader.tsx, src/components/mobile/Headers/ModifyProfileHeader.tsx
1. 마이페이지, 내가쓴글 목록 페이지, 판결전적 페이지, 게시글 목록 페이지, 알림페이지에 스크롤 추가
2. 기존 만들어둔 모바일 헤더들 높이를 50px로 수정
3. global.css에 mobile-scroll 속성 추가
=> style:적응형 페이지들에 스크롤 속성 추가

src/app/home/mobile/component/PostItemMobile.tsx
=> fix:whitespace-nowrap 을 wrap으로 변경

src/app/home/mobile/page.tsx, src/app/post/[postId]/mobile/components/VoteAreaMobile.tsx, src/app/post/[postId]/mobile/page.tsx, src/app/post/[postId]/page.tsx, src/app/post/_component/ContentArea.tsx, src/app/post/_component/VoteArea.tsx, src/app/signUp/mobile/page.tsx, src/app/signUp/page.tsx
1. 모바일 게시글 목록 페이지, 상세 페이지 비로그인상태일때도 보이도록 수정
2. 빌드 에러 수정
3. 간편 회원등록 페이지에서 회원정보(닉네임)가 이미 존재 시 home 페이지로 이동하도록 수정
4. 비로그인 상태일때 투표 제출하기 버튼 클릭 시 alert는 안보이고 로그인 모달만 뜨도록 수정
5. 비로그인 상태일때 자신의 게시글에 투표컴포넌트 안뜨는 에러 수정
=> Fix: 백로그 이슈 및 에러 수정

src/api/postComment.ts, src/app/post/_component/CommentArea.tsx
답글 작성시 새로 작성된 댓글로 스크롤 되는 기능,
댓글 작성시 제일 위로 스크롤 됨.
=> feat: comment scroll

src/app/home/_component/AlarmList.tsx, src/types/get.d.ts
createDateTime -> createdDateTime 수정(스펠링 오류)
=> hotFix: 알람 모달에서 알람이 온 날짜가 오늘날짜로 고정이었던 오류 수정

src/app/post/_component/VoteResult.tsx
=> hotfix: 투표한 사람 없을때 ui 상이한 오류 해결

src/_lib/fetcher.ts, src/app/home/mobile/component/PostTagMobile.tsx, src/app/home/page.tsx, src/app/myPage/_component/MyJudgeItem.tsx, src/app/myPage/judgeRecord/page.tsx, src/app/myPage/mobile/_component/MyJudgeItem.tsx, src/app/myPage/mobile/_component/MyPostItem.tsx, src/app/myPage/mobile/judgeRecord/JudgeRecordMobile.tsx, src/app/myPage/mobile/myPosts/MyPostsMobile.tsx, src/app/myPage/modifyProfile/page.tsx, src/app/myPage/myPosts/page.tsx, src/app/myPage/page.tsx, src/app/post/[postId]/mobile/PostDetailMobile.tsx, src/app/post/[postId]/mobile/components/VoteFormMobile.tsx, src/app/post/_component/PostTag.tsx, src/app/signUp/page.tsx, src/components/mobile/Headers/MainHeader.tsx, src/components/mobile/Headers/MobileLogoHeader.tsx
모바일 메인 헤더 비로그인일때 로그인 버튼 안보이는 오류 해결 필요
모바일 게시글 상세 페이지에서 비로그인일때 투표 컴포넌트 투표 포지션 안보이고 NaN으로 뜨는 에러 해결 필요
=> Style: 모바일 반응형 페이지 작업 완료

src/app/home/mobile/HomeMobile.tsx, src/app/home/mobile/component/DoughnutChartMobile.tsx, src/app/home/mobile/component/ListedPostItemMobile.tsx, src/app/home/mobile/component/PostDeadLineMobile.tsx, src/app/home/mobile/component/PostItemMobile.tsx, src/app/post/[postId]/mobile/PostDetailMobile.tsx, src/app/post/[postId]/mobile/components/ContentAreaMobile.tsx, src/app/post/[postId]/mobile/components/VoteAreaMobile.tsx, src/app/post/[postId]/mobile/components/VoteFormMobile.tsx, src/components/mobile/Headers/MainHeader.tsx
1. 모바일 버전에서 메인, 게시글 상세 페이지에서 닉네임 티어 부분 텍스트 이상하게 보이는 에러 수정
2. 비로그인일때 모바일 메인 헤더 로그인 버튼 안보이던 오류 수정
3. 모바일 투표 컴포넌트 안보이던 에러 수정
=> Fix: 모바일 컴포넌트 에러 수정

src/app/globals.css, src/app/login/mobile/LoginMobile.tsx, src/app/login/page.tsx, src/app/post/[postId]/mobile/components/CommentMobile.tsx, src/app/post/[postId]/mobile/components/VoteAreaMobile.tsx, src/app/post/[postId]/mobile/components/VoteFormMobile.tsx, src/app/post/[postId]/mobile/components/VoteResultMobile.tsx
1. 네이버 로그인 페이지에서 vsgg 로고 클릭하면 메인페이지로 이동하도록 수정
2. 모바일 화면 최소 너비 375px로 변경
3. 모바일 투표 결과 및 투표 컴포넌트에서 제출완료 버튼 오른쪽으로 이동
4. 모바일 게시글 상세 페이지 댓글 부분 사용자 닉네임 8글자보다 많으면 ...추가해서 생략되도록 수정
=> Style: 모바일 댓글 컴포넌트에서 사용자 닉네임 8글자 이상이면 생략되도록 수정

src/app/post/[postId]/mobile/components/VoteChampionItem.tsx, src/app/post/[postId]/mobile/components/VoteResultMobile.tsx, src/app/post/_component/VoteForm.tsx, src/app/post/_component/VoteResult.tsx
=> chore: 빌드 에러 수정

src/app/alert/mobile/page.tsx, src/app/home/mobile/HomeMobile.tsx, src/app/home/page.tsx, src/app/post/write/_component/PostFe.tsx
1. 게시글 작성 페이지에서 영상 첨부 시 파일 형식에 맞는지 검사하는 로직 수정
2. 게시글 작성 요령 가이드 텍스트 수정
3. 모바일 알림 페이지에서 로그인 여부 검사하는 로직 isLogin이 아닌 accessToken으로 수정
=> Fix: 모바일 알림 페이지 오류 수정 및 게시글 작성 페이지 mp4파일 형식 제한 로직, 작성 요령 가이드 수정
